# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kr91Nqov379tzt8n2XADQp1VCcdbMZnW
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = {
    'Season': ['2020', '2021', '2022', '2023', '2024', '2025'],
    'Wins': [28, 32, 35, 33, 31, 34],
    'Goals_Scored': [65, 72, 80, 75, 70, 78],
    'Average_Possession': [52.5, 54.0, 58.5, 56.2, 55.0, 57.8]
}

df = pd.DataFrame(data)

df['Win_Rate (%)'] = (df['Wins'] / 38) * 100

plt.figure(figsize=(10, 6))
sns.lineplot(data=df, x='Season', y='Goals_Scored', marker='o', color='green', label='Goals Scored')
plt.title('Palmeiras: Offensive Evolution (2020-2025)', fontsize=15)
plt.xlabel('Season')
plt.ylabel('Total Goals')
plt.grid(True, linestyle='--', alpha=0.6)
plt.savefig('palmeiras_evolution.png')
plt.show()

print("Analysis successfully completed!")
print(df)

